[package]
name = "learning-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.11.0-rc.2"
hmac = "0.13.0-rc.2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
